limit_req_zone $binary_remote_addr zone=datamoon_gateway_rate:10m rate=5r/s;
limit_conn_zone $binary_remote_addr zone=datamoon_gateway_connections:10m;

map $http_upgrade $datamoon_gateway_is_websocket {
    default 0;
    ~*^websocket$ 1;
}
